### ISSUE TITLE
Question regarding Pore-C results file

### ISSUE THREAD

**Issue by sachingadakh** [nanoporetech/Pore-C-Snakemake#1]
Hello,
   I want to make a summary table of calculation of multiway contacts and distribution of reads containing restriction fragments for 2,3,4 .... , as given Table S1. Pore-C sequencing runs in aggregate in the Pore-C paper 
I want to ask,  is it "contained_fragments" column has the count information about contact order distribution (Table S1) in the file named "*.at.read.parquet" and "*.at.alignment.parquet"?
 Thank you.

**Comment by eharr** [comment]
Hi @sachingadakh,

The read order is stored in the ".at.read.parquet" files as the 'num_pass_aligns' column. Apologies for the inconsistent naming, we settled on 'read_order' while writing the preprint. I'm currently refactoring the code to make things more consistent.

All the best,
Eoghan

**Comment by cjy8709** [comment]
Would you get the same info with the *pairs.gz file in the /pairs directory?
For instance doing something like:

`zgrep -v "^#" pairs.pairs.gz | awk '{print $1}' | sort | uniq -c`

one gets the number of total pairwise contacts per read. And then thats essentially the contact order distribution in TableS1 or PoreC paper? Sorry I'm mostly asking since I'm not used to working with .paraquet type files.

Speaking of TableS1 what is the difference between ≤1 vs. multiway? I didn't understand how one gets less then one contact?

**Comment by eharr** [comment]
@cjy8709 I missed your question earlier, sorry for the late reply.

The zgrep command you listed wouldn't work for 2 reasons i) we append a unique id after the read name so you would need to strip that before doing the uniq and ii) more importantly that command would give the total number of pairwise contacts which is different from contact order. The name is a bit confusing, but contact order is the number of alignments (think restriction fragments) identified per read, and then the binomial coefficient for that number gives the total number of pairwise contacts. This is why there's a ≤1 column in the table - any read that either doesn't align or only has an a single alignment that passes all the filters doesn't yield any pairwise contacts. We included that column to show how many reads are "unproductive" when it comes to generating contact maps.
